name: Update README TOC

on:
  push:
    branches:
      - '*'
#    paths:
#      - 'README.md'

jobs:
  update-toc:
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
